Repository Saloni6111/DSA_Problems, pull requests merged in 2024-10, with the labels that each got.

#81 trapping rain water cpp
  C++/TrappingRainWater.cpp
Labels: hacktoberfest-accepted

#83 Added nQueen code in Java
  Java/nQueen.java
Labels: hacktoberfest-accepted

#82 Solved #66 MergeKSortedLists using c++
  C++/MergeKSortedLists.cpp
Labels: hacktoberfest-accepted

#76 Intersection2arr
  C++/Intersection_2_arrays.cpp
Labels: hacktoberfest-accepted

#69 Set Matrix Zeros Problem in C++
  C++/Set_Matrix_Zeros.cpp
Labels: hacktoberfest-accepted

#70 Added Spiral Matrix - Java Program
  Java/SpiralMatrix.java
Labels: hacktoberfest-accepted

#87 C++ median of two sorted arrays
  C++/Median_2_sorted-arrays.cpp
Labels: hacktoberfest-accepted

#100 Course Schedule
  Python/Course_Schedule.py
Labels: hacktoberfest-accepted

#85 Added Course_Schedule code in Java
  Java/Course_Schedule.java
Labels: hacktoberfest-accepted

#99 Solved Two Sum problem in Java
  Java/twoSum.java
Labels: hacktoberfest-accepted

#98 Longest Increasing Path in a Matrix
  Python/Longest_Increasing_Path_in_a_Matrix.py
Labels: hacktoberfest-accepted

#104 k-th-smallest-in-lexicographical-order.cpp
  -k-th-smallest-in-lexicographical-order.cpp
Labels: hacktoberfest-accepted

#94 Create Palindromic Substrings.py
  Palindromic Substrings.py
Labels: hacktoberfest-accepted

#92 Create FizzBuzz.java
  Java/FizzBuzz.java
Labels: hacktoberfest-accepted

#90 Create Median Of two sorted Array
  Java/MedianOfTwoSortedArray.java
Labels: hacktoberfest-accepted

#75 ADD Solution of loop
  Java/Detect-Loop.java
Labels: hacktoberfest-accepted

#71 Middle of the Linked List
  Java/ListNode.java
Labels: hacktoberfest-accepted

#118 Adder tower_of_hanoi.py
  Python/tower_of_hanoi.py
Labels: hacktoberfest-accepted

#111 Floyd-Warshall Algorithm added in all languages
  C++/floyd-warshall.cpp
  Java/FloydWarshall.java
  JavaScript/floydWarshall.js
  Python/floyd_warshall.py
Labels: hacktoberfest-accepted

#122 Climbing Stairs Program in C
  C/climbing-stairs.c
Labels: hacktoberfest-accepted

#124 rabin-karp algorithm added
  C++/rabin-karp.cpp
  Java/RabinKarp.java
  JavaScript/rabinKarp.js
  Python/rabin_karp.py
Labels: hacktoberfest-accepted

#123 Word Search II
  Python/Word_Search_II.py
Labels: hacktoberfest-accepted

#132 Create Johnson's Algorithm.py
  Johnson's Algorithm.py
Labels: hacktoberfest-accepted

#127 Added LCA in Binary tree
  C++/LCAinBinaryTree.cpp
  C++/NQeenProblem.cpp
  C++/binary_search.cpp
Labels: hacktoberfest-accepted

#149 Create Edit-Distance.java
  Java/Edit-Distance.java
Labels: hacktoberfest-accepted

#145 Added Coin Change Problem Solution
  C++/coin_change.cpp
  C/coin_change.c
  Java/CoinChange.java
Labels: hacktoberfest-accepted

#143 Wildcard-Matching.java
  Java/Wildcard-Matching.java
Labels: hacktoberfest-accepted

#154 Minimum Number of Refueling Stops
  Python/Minimum_number_of_refeuling_stops.py
Labels: hacktoberfest-accepted

#172 Added CodeOfConduct and Licence
  CODE_OF_CONDUCT.md
  LICENSE.txt
Labels: hacktoberfest-accepted

#167 Create Calculator in python.py
  Calculator in python.py
Labels: hacktoberfest-accepted

#164 LRU Cache(#148)
  C++/LRU_Cache.cpp
Labels: hacktoberfest-accepted

#173 Check If Array Pairs Are Divisible by k
  C++/divisible.cpp
Labels: hacktoberfest-accepted

#175 Added Merge Sort Java
  Java/MergeSort.java
Labels: hacktoberfest-accepted

#190 Fixes issue 186 ; queue_using_stack cpp code
  C++/queue_using_stack.cpp
Labels: hacktoberfest-accepted

#189 Add solution for LeetCode problem: Unique Paths (Dynamic Programming)
  Java/.gitignore
  Java/UniquePath1.java
Labels: hacktoberfest-accepted

#188 Fixes issue 187 ; morris_preorder_traversal - added python script
  Python/morris_preorder_traversal.py
Labels: hacktoberfest-accepted

#183 Update Minimum_number_of_refeuling_stops.py
  Python/Minimum_number_of_refeuling_stops.py
Labels: hacktoberfest-accepted

#182 Merging Overlapping Intervals
  C++/merging_overlapping_interfaces.cpp
Labels: hacktoberfest-accepted

#180 OKay Pushed 3_Sum Accept It
  C++/3_Sum.cpp
Labels: hacktoberfest-accepted

#193 Set matrix zero solution added in python and Java
  Java/SetMatrixZeros.java
  Python/Set_Matrix_Zeros.py
Labels: hacktoberfest-accepted

#192 Alien Language the characters are stored in a swquence based on their…
  C++/AlienLanguageSequence.cpp
Labels: hacktoberfest-accepted

#207 Single number java
  Java/MoveZeroes.java
  Java/SingleNumber.java
  Java/SpiralMatrix.java
Labels: hacktoberfest-accepted

#206 Created_group_anagram#200
  C++/Find_duplicate_integer.cpp
  C++/Group_anagram.cpp
  C++/ValidParentheses.cpp
Labels: hacktoberfest-accepted

#205 Created Count number with unique digit #198
  C++/Count_number_unique_digit.cpp
Labels: hacktoberfest-accepted

#204 Find Duplicates
  Java/FindDuplicates.java
Labels: hacktoberfest-accepted

#203 Solution For Trapping Rain Water
  Python/Trapping-Rain-Water.py
Labels: hacktoberfest-accepted

#201 Create QuickSort.java
  QuickSort.java
Labels: hacktoberfest-accepted

#199 Find Duplicate elements in a Stream in Java
  Duplicate elements in a Stream in Java
Labels: hacktoberfest-accepted

#208 Update climbing-stairs.c
  C/climbing-stairs.c
Labels: hacktoberfest-accepted

#210 Update duplicate.c
  C/duplicate.c
Labels: bug, hacktoberfest-accepted

#211 Update coin_change.c
  C/coin_change.c
Labels: hacktoberfest-accepted

#212 Create TowerOfHanoi
  C++/TowerOfHanoi
Labels: hacktoberfest-accepted

#213 Update 3_Sum.cpp
  C++/3_Sum.cpp
Labels: hacktoberfest-accepted

#214 Update BinaryTree.java
  Java/BinaryTree.java
Labels: hacktoberfest-accepted, improvement

#215 Solve/coin change problem
  .gitignore
  C++/coin_change.cpp
Labels: hacktoberfest-accepted

#202 move zeros problem
  Python/move_zeros.py
Labels: hacktoberfest-accepted

#222 Valid number
  C++/Sorted_linkedlist_BST.cpp
  C++/ValidNumber.cpp
Labels: hacktoberfest-accepted

#219 Create Longest2IncreasingSubsequence.java
  Java/Longest2IncreasingSubsequence.java
Labels: hacktoberfest-accepted

#225 Linked List Reversal
  Java/LinkedListReversal.java
Labels: hacktoberfest-accepted

#232 Added Sort Colours
  C++/SortColours.cpp
Labels: hacktoberfest-accepted

#234 Added the solution using Floyed's Cycle detection Algorithm
  C++/DetectCycleInSll.cpp
Labels: hacktoberfest-accepted

#237 Added Segment Tree
  C++/Dynamic-Range-Sum_queries.cpp
Labels: hacktoberfest-accepted

#245 Added Special Matrix problem in C++
  C++/Special_Matrix.cpp
Labels: hacktoberfest-accepted

#244 Implement Queue using Stacks
  Java/QueueUsingStack.java
Labels: hacktoberfest-accepted

#241 Linked List Added Issur Number #228
  C/LinkedList.c
Labels: hacktoberfest-accepted

#240 added string to integer question solution
  C++/stringToInt.cpp
Labels: hacktoberfest-accepted

#248 feat: Add solution for Two Sum problem
  C++/2_Sum.cpp
Labels: hacktoberfest-accepted

#253 Problem Solved: Print Fibonacci Sequeunce
  C++/Print_fibonacci_sequene.cpp
Labels: hacktoberfest-accepted

#252 GCD Subsequences 1
  Java/GCDSubsequences1.java
Labels: hacktoberfest-accepted

#249 Pascals Triangle
  C++/Pascals_Triangle.cpp
  C++/Pascals_Triangle.exe
  Java/Pascals_Triangle.class
  Java/Pascals_Triangle.java
  JavaScript/Pascals_Triangle.js
  Python/Pascals_Triangle.py
Labels: hacktoberfest-accepted

#256 Added:Topo sort using kahn and dfs
  C++/TopologicalSort/UsingDFS.cpp
  C++/TopologicalSort/UsingKahnAlgo.cpp
Labels: hacktoberfest-accepted

#277 feat:cpp - rotate matrix
  C++/rotateMatrix.cpp
Labels: hacktoberfest-accepted

#276 Solved Palindrome Linked List in Java#275
  Java/PalindromeLinkedList.java
Labels: hacktoberfest-accepted

#274 solved merge_sort.py problem as per issue #254
  Python/Merge_sort.py
Labels: hacktoberfest-accepted

#273 Create stack_using_queue.c as per issue #186
  stack_using_queue.c
Labels: hacktoberfest-accepted

#272 Some well-known problems:
  C++/Hard_Palindrome_Reorder.cpp
  C/Kadane_Algorithm.c
  C/Sieve_of_Eratosthene.c
Labels: Hacktoberfest

#271 Solved 3_Sum.cpp problem
  C++/3_Sum.cpp
Labels: hacktoberfest-accepted

#270 Solved 2_Sum.cpp problem of leetcode
  C++/2_Sum.cpp
Labels: hacktoberfest-accepted

#267 Add circularlinklist code
  C/circularlinklist.c
Labels: Hacktoberfest

#266 Create queue.c
  C/queue.c
Labels: Hacktoberfest, hacktoberfest-accepted

#260 Added Binary Search in C++
  C++/Binary_Search.cpp
  C++/output/Binary_Search.exe
Labels: hacktoberfest-accepted

#259 Greetings added
  .github/workflows/greetings.yml
  README.md
Labels: hacktoberfest-accepted

#258 Added Binary Search Algorithm
  C++/BinarySearch.cpp
Labels: hacktoberfest-accepted

#285 Search Algorithms in C
  C/BinarySearch.c
  C/LinearSearch.c
Labels: hacktoberfest-accepted

#284 Algorithm for insertion sort
  Java/InsertionSort.java
Labels: hacktoberfest-accepted

#283 Merge Sort using Linked List
  C++/TopologicalSort/linkedlist/mergesort_LL.cpp
  C++/TopologicalSort/linkedlist/mergesort_LL.exe
  C++/TopologicalSort/linkedlist/mergesortusing_linkedlist.cpp
Labels: hacktoberfest-accepted

#282 Spiral Matrix using cpp
  C++/SpiralMatrix.cpp
  C++/SpiralMatrix.exe
  Java/BinaryTreeVerticalOrder.java
Labels: hacktoberfest-accepted

#281 Solved Sorting Linked List in C++
  C++/Sorting-Linked-List.cpp
Labels: hacktoberfest-accepted

#293 Split Linked List in Part - Java
  Java/SplitLinkedListinParts.java
Labels: hacktoberfest-accepted

#291 #289 added longestpalindromic substring
  C++/LongestPalindromicSubstring.cpp
Labels: hacktoberfest-accepted

#290 Added solution for Kth largest element of the array in Java
  Java/kth.java
Labels: hacktoberfest-accepted

#299 Added Two Sum Problem in javascript folder
  JavaScript/twoSum.js
Labels: hacktoberfest-accepted

#298 Add 3 recusrion problem: sum of array element, linear and binary search (Issue: #296)
  C++/binary_search_using_recursion.cpp
  C++/linear_search_using_recursion.cpp
  C++/sum_of_array_using_recursion.cpp
Labels: hacktoberfest-accepted

#301 Solution added for 'Make Sum Divisible by P' Leetcode Problem 1590
  Java/sum_divisible_by_p.java
Labels: hacktoberfest-accepted

#305 Prasad sarwar
  C/Bubble_Sort_Linkedlist.c
  C/Check_Loop_In_Linkedlist.c
  C/Doubly_Circular_Linkedlist.c
  C/Doubly_Linear_Linkedlist.c
  C/Insertion_Sort_Linkedlist.c
  C/Reverse_Linkedlist.c
  C/Search_In_Linkedlist.c
  C/Selection_Sort_Linkedlist.c
  C/Singly_Circular_Linkedllist.c
  C/Singly_Linear_Linkedlist.c
Labels: hacktoberfest-accepted

#302 Sieve of Eratosthenes Solution Added #295
  Java/SieveOfEratosthenes.java
Labels: hacktoberfest-accepted

#313 Added solution for Valid Parenthesis problem
  JavaScript/validParenthesis.js
Labels: hacktoberfest-accepted

#312 solution of reverse the array without making any copy
  C++/reverse-array.cpp
Labels: hacktoberfest-accepted

#309 Added randomized quick sort
  C/Randomized_Quick_Sort.c
Labels: hacktoberfest-accepted

#308 solution for median of two sorted arrays is added
  Python/Median_of_Two_Sorted_Arrays.py
Labels: hacktoberfest-accepted

#315 Solution to the Problem 1598. Crawler Log Folder on LC
  C++/output/crawler_log_folder.cpp
Labels: hacktoberfest-accepted

#323 feat: solution for climbing stairs problem in Python
  Python/climbing_stairs.py
Labels: hacktoberfest-accepted

#322 feat: solution for power sum problem in Java
  Java/PowerSum.java
Labels: hacktoberfest-accepted

#321 feat: solution for knights tour backtracking problem in Java
  Java/KnightsTour.java
Labels: hacktoberfest-accepted

#329 Added merge sort in C
  C/MergeSort.c
Labels: hacktoberfest-accepted

#330 Added Anagram of two strings
  .gitignore
  Java/Anagram.java
Labels: hacktoberfest-accepted

#335 feat: solution for optimal_binary_search_tree
  Python/optimal_binary_search_tree.py
Labels: hacktoberfest-accepted

#334 feat: solution for kth order statistic
  Python/kth_order_statistic.py
Labels: hacktoberfest-accepted

#336 Added Linked List Cycle problem in cpp
  C++/linkedListCycle.cpp
Labels: hacktoberfest-accepted

#338 dsa problem added using javascript for binary search
  JavaScript/binary_search.js
Labels: hacktoberfest-accepted

#340 #337 - Add Best Time to Buy and Sell Stock solution using java
  Java/BestTimeToBuySellStock.java
Labels: hacktoberfest-accepted

#343 Added Reverse a Stack in Java
  Java/ReverseAstack.java
Labels: hacktoberfest-accepted

#344 uses Memoization and reduces space
  C++/AdjacentBitCounts.cpp
  C++/LCAinBinaryTree.cpp
  C++/ValidParentheses.cpp
Labels: hacktoberfest-accepted

#354 added graph problem of connected components
  C++/connected-components.cpp
Labels: DSA
